language: c

sudo: true

os:
  - linux
  - osx

env:
  - FISH_PPA=nightly-master
  - FISH_PPA=release-2
  
matrix:
  exclude:
    - os: osx
      env: FISH_PPA=nightly-master

before_install:
  - ./prepare-ci.sh
  - fish --version

before_script:
  - git config --global user.email "tuvistavie+fundle@gmail.com"
  - git config --global user.name "Fundle"

script: make test
