language: c

sudo: true

env:
  - FISH_PPA=nightly-master
  - FISH_PPA=release-2

before_install:
  - make prepare

before_script:
  - git config --global user.email "tuvistavie+fundle@gmail.com"
  - git config --global user.name "Fundle"

script: make test
